BEGIN;

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL CHECK (length(trim(full_name)) >= 2),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL CHECK (length(trim(name)) >= 2),
  price_cents numeric(12, 0) NOT NULL CHECK (price_cents >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id),
  status text NOT NULL
    CHECK (status IN ('pending', 'completed', 'cancelled', 'refunded')),
  total_cents numeric(12, 0) NOT NULL CHECK (total_cents >= 0),
  shipping_country char(2) NOT NULL
    CHECK (shipping_country ~ '^[A-Z]{2}$'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id),
  quantity integer NOT NULL CHECK (quantity BETWEEN 1 AND 100),
  unit_price_cents numeric(12, 0) NOT NULL
    CHECK (unit_price_cents >= 0),
  line_total_cents numeric(12, 0) NOT NULL
    CHECK (line_total_cents = unit_price_cents * quantity),
  UNIQUE (order_id, product_id)
);

CREATE TABLE idempotency_records (
  idempotency_key text PRIMARY KEY,
  order_id bigint NOT NULL UNIQUE REFERENCES orders(id) ON DELETE CASCADE,
  request_hash char(64) NOT NULL CHECK (length(request_hash) = 64),
  response_status integer NOT NULL CHECK (response_status BETWEEN 100 AND 599),
  response_body jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMIT;
