import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddCheckoutAndJobs1726100000000 implements MigrationInterface {
  name = 'AddCheckoutAndJobs1726100000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "users"
        ADD COLUMN "balance_cents" integer NOT NULL DEFAULT 0
    `);
    await queryRunner.query(`
      ALTER TABLE "users"
        ADD CONSTRAINT "CHK_users_balance_cents_nonneg"
        CHECK ("balance_cents" >= 0)
    `);

    await queryRunner.query(`
      ALTER TABLE "products"
        ADD COLUMN "stock" integer NOT NULL DEFAULT 0
    `);
    await queryRunner.query(`
      ALTER TABLE "products"
        ADD CONSTRAINT "CHK_products_stock_nonneg"
        CHECK ("stock" >= 0)
    `);

    await queryRunner.query(`
      CREATE TABLE "jobs" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "type" text NOT NULL CHECK ("type" IN ('send_receipt')),
        "payload" jsonb NOT NULL DEFAULT '{}',
        "status" text NOT NULL DEFAULT 'pending'
          CHECK ("status" IN ('pending', 'done')),
        "processed" integer NOT NULL DEFAULT 0 CHECK ("processed" >= 0),
        "worker_id" text,
        "order_id" bigint REFERENCES "orders"("id") ON DELETE CASCADE,
        "created_at" timestamptz NOT NULL DEFAULT now(),
        "processed_at" timestamptz
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_jobs_pending"
        ON "jobs" ("id")
        WHERE "status" = 'pending'
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_jobs_pending"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "jobs"`);
    await queryRunner.query(
      `ALTER TABLE "products" DROP CONSTRAINT IF EXISTS "CHK_products_stock_nonneg"`,
    );
    await queryRunner.query(
      `ALTER TABLE "products" DROP COLUMN IF EXISTS "stock"`,
    );
    await queryRunner.query(
      `ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "CHK_users_balance_cents_nonneg"`,
    );
    await queryRunner.query(
      `ALTER TABLE "users" DROP COLUMN IF EXISTS "balance_cents"`,
    );
  }
}
