import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1726000000000 implements MigrationInterface {
  name = 'InitialSchema1726000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "email" text NOT NULL UNIQUE,
        "full_name" text NOT NULL CHECK (length(trim(full_name)) >= 2),
        "created_at" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "products" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "name" text NOT NULL CHECK (length(trim(name)) >= 2),
        "price_cents" integer NOT NULL CHECK ("price_cents" >= 0),
        "is_active" boolean NOT NULL DEFAULT true,
        "created_at" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "orders" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" bigint NOT NULL REFERENCES "users"("id") ON DELETE RESTRICT,
        "status" text NOT NULL
          CHECK ("status" IN ('pending', 'completed', 'cancelled', 'refunded')),
        "total_cents" integer NOT NULL CHECK ("total_cents" >= 0),
        "shipping_country" char(2) NOT NULL
          CHECK ("shipping_country" ~ '^[A-Z]{2}$'),
        "created_at" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "order_items" (
        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "order_id" bigint NOT NULL REFERENCES "orders"("id") ON DELETE CASCADE,
        "product_id" bigint NOT NULL REFERENCES "products"("id") ON DELETE RESTRICT,
        "quantity" integer NOT NULL CHECK ("quantity" BETWEEN 1 AND 100),
        "unit_price_cents" integer NOT NULL CHECK ("unit_price_cents" >= 0),
        "line_total_cents" integer NOT NULL
          CHECK ("line_total_cents" = "unit_price_cents" * "quantity"),
        CONSTRAINT "UQ_order_items_order_product" UNIQUE ("order_id", "product_id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "idempotency_records" (
        "idempotency_key" text PRIMARY KEY,
        "order_id" bigint NOT NULL UNIQUE REFERENCES "orders"("id") ON DELETE CASCADE,
        "request_hash" char(64) NOT NULL CHECK (length(request_hash) = 64),
        "response_status" integer NOT NULL CHECK ("response_status" BETWEEN 100 AND 599),
        "response_body" jsonb NOT NULL,
        "created_at" timestamptz NOT NULL DEFAULT now()
      )
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_orders_user_created_at"
        ON "orders" ("user_id", "created_at" DESC)
        INCLUDE ("id", "status", "total_cents")
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_orders_pending_created_at"
        ON "orders" ("created_at" ASC)
        INCLUDE ("id", "user_id", "total_cents")
        WHERE "status" = 'pending'
    `);

    await queryRunner.query(`
      CREATE INDEX "idx_orders_country_status_created_at"
        ON "orders" ("shipping_country", "status", "created_at" DESC)
        INCLUDE ("id", "total_cents")
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_orders_country_status_created_at"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_orders_pending_created_at"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "idx_orders_user_created_at"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "idempotency_records"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "order_items"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "orders"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "products"`);
    await queryRunner.query(`DROP TABLE IF EXISTS "users"`);
  }
}
